name: Java CI with Maven

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    name: Java ${{ matrix.java }} compile
    steps:
    - name: Git Checkout
      uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin' # See 'Supported distributions' for available options
        cache: maven
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.6
    - name: Install xvfb
      run: sudo apt-get install xvfb
    - name: Build NatTable with Javadoc
      run: xvfb-run mvn clean compile javadoc:aggregate verify
